name: build-receiver

on:
  push:
    branches:
      - "main"
    paths:
      - '.'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#       name: Spin up rabbitmq
#        run: docker compose up -d rabbitmq
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/receiver:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/receiver:${{github.run_number}} \
            -f ./Receive/Dockerfile \
            --network host \
            .
      -
        name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/receiver:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/receiver:${{github.run_number}}

#      -
#        name: Tear down rabbitmq
#        if: always()
#        run: docker compose down rabbitmq
